
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/elazarl/go-bindata-assetfs"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/gopherjs/gopherjs"

[[constraint]]
  branch = "master"
  name = "github.com/improbable-eng/grpc-web"

[[constraint]]
  branch = "master"
  name = "github.com/johanbrandhorst/protobuf"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.5.1"

[[constraint]]
  branch = "master"
  name = "honnef.co/go/js/dom"

[[constraint]]
  branch = "master"
  name = "honnef.co/go/js/xhr"

[[constraint]]
  branch = "master"
  name = "myitcv.io/highlightjs"

[[constraint]]
  branch = "master"
  name = "myitcv.io/immutable"

[[constraint]]
  branch = "master"
  name = "myitcv.io/react"
