version: 2
jobs:
  generate:
    docker:
      - image: 'jfbrandhorst/docker-go-protobuf'
    working_directory: /go/src/github.com/johanbrandhorst/grpcweb-example
    steps:
      - checkout
      - run:
          name: Install go dependencies
          command: make install
      - run:
          name: Regenerate
          command: make regenerate
  build:
    docker:
      - image: 'golang:latest'
    working_directory: /go/src/github.com/johanbrandhorst/grpcweb-example
    steps:
      - checkout
      - run: CGO_ENABLED=0 go build main.go
workflows:
  version: 2
  build-and-test:
    jobs:
      - generate
      - build:
          requires:
            - generate
