version: 2
jobs:
  generate:
    docker:
      - image: 'golang:latest'
    working_directory: /go/src/github.com/johanbrandhorst/grpcweb-example
    steps:
      - checkout
      - run:
          name: Install protoc
          environment:
            PROTOBUF_VERSION: "3.5.1"
          command: >
            apt-get update

            apt-get install -y unzip git wget python3

            rm -rf /var/lib/apt/lists/*

            wget
            https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip

            unzip protoc-${PROTOBUF_VERSION}-linux-x86_64.zip -d /usr/local

            rm protoc-${PROTOBUF_VERSION}-linux-x86_64.zip

            apt-get remove -y wget unzip

            apt-get autoremove -y
      - run:
          name: Install go dependencies
          command: make install
      - run:
          name: Regenerate
          command: make regenerate
  build:
    docker:
      - image: 'golang:latest'
    working_directory: /go/src/github.com/johanbrandhorst/grpcweb-example
    steps:
      - checkout
      - run: CGO_ENABLED=0 go build main.go
workflows:
  version: 2
  build-and-test:
    jobs:
      - generate
      - build:
          requires:
            - generate
